// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(NaqlahContext))]
    partial class NaqlahContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            /* =========================
             * ENTITY DEFINITIONS
             * ========================= */

            modelBuilder.Entity("Domain.Models.AssistanWork", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ArabicName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EnglishName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.HasKey("Id");
                b.ToTable("NA_AssistanWork");
            });

            modelBuilder.Entity("Domain.Models.Assistant", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name").IsRequired();
                b.Property<string>("PhoneNumber").IsRequired();
                b.Property<string>("Address").IsRequired();
                b.Property<string>("FrontIdentityImagePath").IsRequired();
                b.Property<string>("BackIdentityImagePath").IsRequired();
                b.Property<string>("IdentityNumber").IsRequired();

                b.Property<DateTime>("IdentityExpirationDate")
                    .HasColumnType("datetime2");

                b.Property<int>("AssistanWorkId");
                b.Property<int?>("DeliveryManId");

                b.HasKey("Id");
                b.HasIndex("AssistanWorkId");
                b.HasIndex("DeliveryManId");

                b.ToTable("NA_Assistant");
            });

            modelBuilder.Entity("Domain.Models.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("PhoneNumber").IsRequired();
                b.Property<string>("AndriodDevice").IsRequired();
                b.Property<string>("IosDevice").IsRequired();

                b.Property<int>("CustomerType");
                b.Property<int>("UserId");

                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();

                b.ToTable("NA_Customer");
            });

            modelBuilder.Entity("Domain.Models.DeliveryMan", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("FullName").IsRequired();
                b.Property<string>("PhoneNumber").IsRequired();
                b.Property<string>("Address").IsRequired();
                b.Property<string>("PersonalImagePath").IsRequired();

                b.Property<bool>("Active");
                b.Property<int>("DeliveryState");
                b.Property<int>("DeliveryType");
                b.Property<int>("DeliveryLicenseType");

                b.Property<int>("UserId");

                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();

                b.ToTable("NA_DeliveryMan");
            });

            modelBuilder.Entity("Domain.Models.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("OrderNumber").IsRequired();
                b.Property<int>("CustomerId");
                b.Property<int>("OrderStatus");
                b.Property<int>("OrderType");
                b.Property<decimal>("Total")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("OrderPackageId");

                b.HasKey("Id");
                b.HasIndex("OrderPackageId");

                b.ToTable("NA_Order");
            });

            modelBuilder.Entity("Domain.Models.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name").HasMaxLength(256);
                b.Property<string>("NormalizedName").HasMaxLength(256);
                b.Property<string>("ArabicName").IsRequired();
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken();

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("Na_Roles");

                b.HasData(
                    new { Id = 1, Name = "Admin", NormalizedName = "ADMIN", ArabicName = "أدمن" },
                    new { Id = 2, Name = "DeliveryMan", NormalizedName = "DELIVERYMAN", ArabicName = "الطيار" },
                    new { Id = 3, Name = "Customer", NormalizedName = "CUSTOMER", ArabicName = "العميل" }
                );
            });

            modelBuilder.Entity("Domain.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("UserName").HasMaxLength(256);
                b.Property<string>("NormalizedUserName").HasMaxLength(256);
                b.Property<string>("Email").HasMaxLength(256);
                b.Property<string>("NormalizedEmail").HasMaxLength(256);
                b.Property<string>("PasswordHash");

                b.Property<bool>("IsActive");
                b.Property<bool>("IsDeleted");

                b.HasKey("Id");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("NA_User");
            });

            /* =========================
             * RELATIONSHIPS
             * ========================= */

            modelBuilder.Entity("Domain.Models.Assistant", b =>
            {
                b.HasOne("Domain.Models.AssistanWork", "AssistanWork")
                    .WithMany()
                    .HasForeignKey("AssistanWorkId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.Models.DeliveryMan", "DeliveryMan")
                    .WithMany("Assistants")
                    .HasForeignKey("DeliveryManId")
                    .OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("Domain.Models.Customer", b =>
            {
                b.HasOne("Domain.Models.User", "User")
                    .WithOne("Customer")
                    .HasForeignKey("Domain.Models.Customer", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Domain.Models.DeliveryMan", b =>
            {
                b.HasOne("Domain.Models.User", "User")
                    .WithOne("DeliveryMan")
                    .HasForeignKey("Domain.Models.DeliveryMan", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

#pragma warning restore 612, 618
        }
    }
}
